### ISSUE TITLE
Fails to compile with clojure 1.8

### ISSUE THREAD

**Issue by lapooh** [clj-commons/gloss#44]
When I compile project under clojure 1.8, i get this error

```
#error {
 :cause IllegalName: compile__stub.gloss.data.bytes.core.gloss.data.bytes.core/MultiBufferSequence
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.NoClassDefFoundError: IllegalName: compile__stub.gloss.data.bytes.core.gloss.data.bytes.core/MultiBufferSequence, compiling:(gloss/data/bytes/core.clj:78:1)
   :at [clojure.lang.Compiler analyzeSeq Compiler.java 6875]}
  {:type java.lang.NoClassDefFoundError
   :message IllegalName: compile__stub.gloss.data.bytes.core.gloss.data.bytes.core/MultiBufferSequence
   :at [java.lang.ClassLoader preDefineClass ClassLoader.java 654]}]

and so on...
```

Similar issue is https://github.com/ztellman/aleph/issues/189.
Please upgrade potemkin.

**Comment by ztellman** [comment]
Thanks for bringing this to my attention.

**Comment by mithrandi** [comment]
Fixed in #47.
